In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler


In [2]:
data = pd.read_csv('GOOG.csv', date_parser = True)
data.tail()

Date         Open         High          Low        Close  \
4175  2021-03-22  2041.839966  2057.989990  2026.069946  2038.589966   
4176  2021-03-23  2051.699951  2072.302002  2039.219971  2052.959961   
4177  2021-03-24  2065.370117  2078.209961  2041.555054  2045.060059   
4178  2021-03-25  2044.810059  2058.870117  2010.729980  2044.359985   
4179  2021-03-26  2038.859985  2050.989990  2014.020020  2035.550049   

        Adj Close   Volume  
4175  2038.589966  1954800  
4176  2052.959961  1367000  
4177  2045.060059  1154000  
4178  2044.359985  1418900  
4179  2035.550049  1493500

In [3]:
data_training = data[data['Date']<'2021-01-01'].copy()
data_training

Date         Open         High          Low        Close  \
0     2004-08-19    49.813290    51.835709    47.800831    49.982655   
1     2004-08-20    50.316402    54.336334    50.062355    53.952770   
2     2004-08-23    55.168217    56.528118    54.321388    54.495735   
3     2004-08-24    55.412300    55.591629    51.591621    52.239197   
4     2004-08-25    52.284027    53.798351    51.746044    52.802086   
...          ...          ...          ...          ...          ...   
4117  2020-12-24  1735.000000  1746.000000  1729.109985  1738.849976   
4118  2020-12-28  1751.635010  1790.728027  1746.334961  1776.089966   
4119  2020-12-29  1787.790039  1792.439941  1756.089966  1758.719971   
4120  2020-12-30  1762.010010  1765.094971  1725.599976  1739.520020   
4121  2020-12-31  1735.420044  1758.930054  1735.420044  1751.880005   

        Adj Close    Volume  
0       49.982655  44871361  
1       53.952770  22942874  
2       54.495735  18342897  
3       52.239197  15319808  
4       52.802086   9232276  
...           ...       ...  
4117  1738.849976    346800  
4118  1776.089966   1393000  
4119  1758.719971   1299400  
4120  1739.520020   1306100  
4121  1751.880005   1011900  

[4122 rows x 7 columns]

In [4]:
data_test = data[data['Date']>='2021-01-01'].copy()
data_test


Date         Open         High          Low        Close  \
4122  2021-01-04  1757.540039  1760.650024  1707.849976  1728.239990   
4123  2021-01-05  1725.000000  1747.670044  1718.015015  1740.920044   
4124  2021-01-06  1702.630005  1748.000000  1699.000000  1735.290039   
4125  2021-01-07  1740.060059  1788.400024  1737.050049  1787.250000   
4126  2021-01-08  1787.979980  1809.839966  1773.535034  1807.209961   
4127  2021-01-11  1786.069946  1794.314941  1760.520020  1766.719971   
4128  2021-01-12  1753.920044  1778.040039  1725.310059  1746.550049   
4129  2021-01-13  1738.579956  1765.035034  1738.010010  1754.400024   
4130  2021-01-14  1753.619995  1775.010010  1733.400024  1740.180054   
4131  2021-01-15  1738.189941  1756.000000  1721.550049  1736.189941   
4132  2021-01-19  1752.250000  1809.275024  1741.459961  1790.859985   
4133  2021-01-20  1831.459961  1903.709961  1825.530029  1886.900024   
4134  2021-01-21  1898.000000  1934.859985  1887.109985  1891.250000   
4135  2021-01-22  1895.680054  1910.949951  1881.760010  1901.050049   
4136  2021-01-25  1920.670044  1929.579956  1867.530029  1899.400024   
4137  2021-01-26  1888.839966  1925.000000  1884.244995  1917.239990   
4138  2021-01-27  1882.530029  1890.000000  1809.000000  1830.790039   
4139  2021-01-28  1843.939941  1898.829956  1842.640015  1863.109985   
4140  2021-01-29  1846.170044  1857.280029  1810.199951  1835.739990   
4141  2021-02-01  1853.569946  1922.391968  1850.930054  1901.349976   
4142  2021-02-02  1922.560059  1955.760010  1914.489990  1927.510010   
4143  2021-02-03  2073.000000  2116.500000  2018.380005  2070.070068   
4144  2021-02-04  2068.889893  2078.550049  2042.589966  2062.370117   
4145  2021-02-05  2070.000000  2102.510010  2059.330078  2098.000000   
4146  2021-02-08  2105.909912  2123.547119  2072.000000  2092.909912   
4147  2021-02-09  2078.540039  2105.129883  2078.540039  2083.510010   
4148  2021-02-10  2094.209961  2108.370117  2063.090088  2095.379883   
4149  2021-02-11  2099.510010  2102.030029  2077.320068  2095.889893   
4150  2021-02-12  2090.250000  2108.820068  2083.129883  2104.110107   
4151  2021-02-16  2104.360107  2152.679932  2104.360107  2121.899902   
4152  2021-02-17  2100.000000  2133.659912  2098.919922  2128.310059   
4153  2021-02-18  2110.389893  2132.735107  2103.709961  2117.199951   
4154  2021-02-19  2119.270020  2130.530029  2097.409912  2101.139893   
4155  2021-02-22  2067.000000  2091.419922  2062.139893  2064.879883   
4156  2021-02-23  2025.010010  2082.010010  2002.020020  2070.860107   
4157  2021-02-24  2041.829956  2100.780029  2038.130005  2095.169922   
4158  2021-02-25  2067.449951  2094.879883  2021.290039  2031.359985   
4159  2021-02-26  2050.520020  2071.010010  2016.060059  2036.859985   
4160  2021-03-01  2056.520020  2086.520020  2046.099976  2081.510010   
4161  2021-03-02  2076.189941  2104.370117  2071.260010  2075.840088   
4162  2021-03-03  2067.209961  2088.518066  2010.000000  2026.709961   
4163  2021-03-04  2023.369995  2089.239990  2020.270020  2049.090088   
4164  2021-03-05  2073.120117  2118.110107  2046.415039  2108.540039   
4165  2021-03-08  2101.129883  2128.810059  2021.609985  2024.170044   
4166  2021-03-09  2070.000000  2078.040039  2047.829956  2052.699951   
4167  2021-03-10  2071.760010  2075.000000  2033.369995  2055.030029   
4168  2021-03-11  2074.060059  2125.699951  2072.379883  2114.770020   
4169  2021-03-12  2085.000000  2090.260010  2047.550049  2061.919922   
4170  2021-03-15  2062.300049  2067.060059  2043.510010  2066.489990   
4171  2021-03-16  2078.989990  2123.560059  2070.000000  2092.520020   
4172  2021-03-17  2076.030029  2109.780029  2054.000000  2091.080078   
4173  2021-03-18  2061.000000  2075.500000  2033.550049  2036.219971   
4174  2021-03-19  2042.050049  2053.100098  2017.680054  2043.199951   
4175  2021-03-22  2041.839966  2057.989990  2026.069946  2038.589966   
4176  2021-03-23  2051.699951  2072.302002  2039.219

In [5]:
training_data = data_training.drop(['Date', 'Adj Close'], axis = 1)
training_data.head()

Open       High        Low      Close    Volume
0  49.813290  51.835709  47.800831  49.982655  44871361
1  50.316402  54.336334  50.062355  53.952770  22942874
2  55.168217  56.528118  54.321388  54.495735  18342897
3  55.412300  55.591629  51.591621  52.239197  15319808
4  52.284027  53.798351  51.746044  52.802086   9232276

In [6]:
scaler = MinMaxScaler()
training_data = scaler.fit_transform(training_data)
training_data

array([[2.27303632e-04, 6.43283156e-04, 0.00000000e+00, 9.24472018e-05,
        5.43577158e-01],
       [5.10729413e-04, 2.03521039e-03, 1.27420629e-03, 2.32514214e-03,
        2.77885876e-01],
       [3.24397659e-03, 3.25522693e-03, 3.67386538e-03, 2.63049229e-03,
        2.22151352e-01],
       ...,
       [9.79308338e-01, 9.69518841e-01, 9.62498190e-01, 9.61044247e-01,
        1.56478852e-02],
       [9.64785280e-01, 9.54297762e-01, 9.45319271e-01, 9.50246667e-01,
        1.57290641e-02],
       [9.49805947e-01, 9.50866174e-01, 9.50852174e-01, 9.57197618e-01,
        1.21644600e-02]])

In [7]:
X_train = []
y_train = []

In [8]:
training_data.shape[0]

4122

In [9]:
for i in range(60, training_data.shape[0]):
    X_train.append(training_data[i-60:i])
    y_train.append(training_data[i, 0])

In [10]:
X_train, y_train = np.array(X_train), np.array(y_train)

In [11]:
X_train.shape, y_train.shape

((4062, 60, 5), (4062,))

In [17]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout

In [45]:
model = Sequential()
model.add(LSTM(units = 10, activation = 'relu', return_sequences = True, input_shape = (X_train.shape[1], 5)))
model.add(Dropout(0.2))

model.add(LSTM(units = 10, activation = 'relu', return_sequences = True))
model.add(Dropout(0.3))

model.add(LSTM(units = 10, activation = 'relu', return_sequences = True))
model.add(Dropout(0.4))

model.add(LSTM(units = 10, activation = 'relu'))
model.add(Dropout(0.5))


model.add(Dense(units=1))


In [46]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 60, 10)            640       
_________________________________________________________________
dropout_4 (Dropout)          (None, 60, 10)            0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 60, 10)            840       
_________________________________________________________________
dropout_5 (Dropout)          (None, 60, 10)            0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 60, 10)            840       
_________________________________________________________________
dropout_6 (Dropout)          (None, 60, 10)            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 10)                840       
__________

In [47]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [48]:
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
4062/4062 [==============================] - 30s 7ms/step - loss: 0.0696
Epoch 2/10
4062/4062 [==============================] - 27s 7ms/step - loss: 0.0239
Epoch 3/10
4062/4062 [==============================] - 25s 6ms/step - loss: 0.0176
Epoch 4/10
4062/4062 [==============================] - 25s 6ms/step - loss: 0.0155
Epoch 5/10
4062/4062 [==============================] - 28s 7ms/step - loss: 0.0135
Epoch 6/10
4062/4062 [==============================] - 26s 6ms/step - loss: 0.0134
Epoch 7/10
4062/4062 [==============================] - 21s 5ms/step - loss: 0.0135
Epoch 8/10
4062/4062 [==============================] - 22s 5ms/step - loss: 0.0121
Epoch 9/10
4062/4062 [==============================] - 25s 6ms/step - loss: 0.0119
Epoch 10/10
4062/4062 [==============================] - 27s 7ms/step - loss: 0.0115


In [65]:
data_test.head()

Date         Open         High          Low        Close  \
4122  2021-01-04  1757.540039  1760.650024  1707.849976  1728.239990   
4123  2021-01-05  1725.000000  1747.670044  1718.015015  1740.920044   
4124  2021-01-06  1702.630005  1748.000000  1699.000000  1735.290039   
4125  2021-01-07  1740.060059  1788.400024  1737.050049  1787.250000   
4126  2021-01-08  1787.979980  1809.839966  1773.535034  1807.209961   

        Adj Close   Volume  
4122  1728.239990  1901900  
4123  1740.920044  1145300  
4124  1735.290039  2602100  
4125  1787.250000  2265000  
4126  1807.209961  2050600

In [66]:
data_training.tail(60)

Date         Open         High          Low        Close  \
4062  2020-10-07  1464.290039  1468.959961  1436.000000  1460.290039   
4063  2020-10-08  1465.089966  1490.000000  1465.089966  1485.930054   
4064  2020-10-09  1494.699951  1516.520020  1489.449951  1515.219971   
4065  2020-10-12  1543.000000  1593.859985  1532.569946  1569.150024   
4066  2020-10-13  1583.729980  1590.000000  1563.199951  1571.680054   
4067  2020-10-14  1578.589966  1587.683960  1550.530029  1568.079956   
4068  2020-10-15  1547.150024  1575.104980  1545.030029  1559.130005   
4069  2020-10-16  1565.849976  1581.130005  1563.000000  1573.010010   
4070  2020-10-19  1580.459961  1588.150024  1528.000000  1534.609985   
4071  2020-10-20  1527.050049  1577.500000  1525.670044  1555.930054   
4072  2020-10-21  1573.329956  1618.729980  1571.630005  1593.310059   
4073  2020-10-22  1593.050049  1621.989990  1585.000000  1615.329956   
4074  2020-10-23  1626.069946  1642.359985  1620.510010  1641.000000   
4075  2020-10-26  1625.010010  1638.239990  1576.500000  1590.449951   
4076  2020-10-27  1595.670044  1606.844971  1582.780029  1604.260010   
4077  2020-10-28  1559.739990  1561.349976  1514.619995  1516.619995   
4078  2020-10-29  1522.359985  1593.709961  1522.239990  1567.239990   
4079  2020-10-30  1672.109985  1687.000000  1604.459961  1621.010010   
4080  2020-11-02  1628.160034  1660.770020  1616.030029  1626.030029   
4081  2020-11-03  1631.780029  1661.699951  1616.619995  1650.209961   
4082  2020-11-04  1710.280029  1771.364990  1706.030029  1749.130005   
4083  2020-11-05  1781.000000  1793.640015  1750.510010  1763.369995   
4084  2020-11-06  1753.949951  1772.430054  1740.349976  1761.750000   
4085  2020-11-09  1790.900024  1818.060059  1760.020020  1763.000000   
4086  2020-11-10  1731.089966  1763.000000  1717.300049  1740.390015   
4087  2020-11-11  1750.000000  1764.219971  1747.364990  1752.709961   
4088  2020-11-12  1747.630005  1768.270020  1745.599976  1749.839966   
4089  2020-11-13  1757.630005  1781.040039  1744.550049  1777.020020   
4090  2020-11-16  1771.699951  1799.069946  1767.689941  1781.380005   
4091  2020-11-17  1776.939941  1785.000000  1767.000000  1770.150024   
4092  2020-11-18  1765.229980  1773.469971  1746.140015  1746.780029   
4093  2020-11-19  1738.380005  1769.589966  1737.005005  1763.920044   
4094  2020-11-20  1765.209961  1774.000000  1741.859985  1742.189941   
4095  2020-11-23  1749.599976  1753.900024  1717.719971  1734.859985   
4096  2020-11-24  1730.500000  1771.599976  1727.689941  1768.880005   
4097  2020-11-25  1772.890015  1778.540039  1756.540039  1771.430054   
4098  2020-11-27  1773.089966  1804.000000  1772.439941  1793.189941   
4099  2020-11-30  1781.183960  1788.064941  1755.000000  1760.739990   
4100  2020-12-01  1774.369995  1824.829956  1769.369995  1798.099976   
4101  2020-12-02  1798.099976  1835.650024  1789.473022  1827.949951   
4102  2020-12-03  1824.010010  1847.199951  1822.650024  1826.770020   
4103  2020-12-04  1824.520020  1833.160034  1816.989990  1827.989990   
4104  2020-12-07  1819.000000  1832.369995  1805.780029  1819.479980   
4105  2020-12-08  1810.099976  1821.900024  1796.204956  1818.550049   
4106  2020-12-09  1812.010010  1834.270020  1767.810059  1784.130005   
4107  2020-12-10  1769.800049  1781.310059  1740.319946  1775.329956   
4108  2020-12-11  1763.060059  1784.449951  1760.000000  1781.770020   
4109  2020-12-14  1775.000000  1797.390015  1757.214966  1760.060059   
4110  2020-12-15  1764.420044  1771.420044  1749.949951  1767.770020   
4111  2020-12-16  1772.880005  1773.000000  1756.079956  1763.000000   
4112  2020-12-17  1768.510010  1771.784058  1738.660034  1747.900024   
4113  2020-12-18  1754.180054  1755.109985  1720.219971  1731.010010   
4114  2020-12-21  1713.510010  1740.849976  1699.000000  1739.369995   
4115  2020-12-22  1734.430054  1737.405029  1712.574951  1723.500000   
4116  2020-12-23  1728.109985  1747.989990  1725.040

In [67]:
past_60_days = data_training.tail(60)

In [68]:
df = past_60_days.append(data_test, ignore_index = True)
df

Date         Open         High          Low        Close  \
0    2020-10-07  1464.290039  1468.959961  1436.000000  1460.290039   
1    2020-10-08  1465.089966  1490.000000  1465.089966  1485.930054   
2    2020-10-09  1494.699951  1516.520020  1489.449951  1515.219971   
3    2020-10-12  1543.000000  1593.859985  1532.569946  1569.150024   
4    2020-10-13  1583.729980  1590.000000  1563.199951  1571.680054   
..          ...          ...          ...          ...          ...   
113  2021-03-22  2041.839966  2057.989990  2026.069946  2038.589966   
114  2021-03-23  2051.699951  2072.302002  2039.219971  2052.959961   
115  2021-03-24  2065.370117  2078.209961  2041.555054  2045.060059   
116  2021-03-25  2044.810059  2058.870117  2010.729980  2044.359985   
117  2021-03-26  2038.859985  2050.989990  2014.020020  2035.550049   

       Adj Close   Volume  
0    1460.290039  1746200  
1    1485.930054  1187800  
2    1515.219971  1435300  
3    1569.150024  2482600  
4    1571.680054  1601000  
..           ...      ...  
113  2038.589966  1954800  
114  2052.959961  1367000  
115  2045.060059  1154000  
116  2044.359985  1418900  
117  2035.550049  1493500  

[118 rows x 7 columns]

In [69]:
df = df.drop(['Date', 'Adj Close'], axis = 1)
df.head()

Open         High          Low        Close   Volume
0  1464.290039  1468.959961  1436.000000  1460.290039  1746200
1  1465.089966  1490.000000  1465.089966  1485.930054  1187800
2  1494.699951  1516.520020  1489.449951  1515.219971  1435300
3  1543.000000  1593.859985  1532.569946  1569.150024  2482600
4  1583.729980  1590.000000  1563.199951  1571.680054  1601000

In [70]:
inputs = scaler.transform(df)
inputs

array([[0.79706613, 0.78945962, 0.78215049, 0.7932146 , 0.02106143],
       [0.79751677, 0.80117117, 0.7985406 , 0.80763391, 0.01429571],
       [0.81419741, 0.81593306, 0.8122657 , 0.82410584, 0.01729449],
       [0.84140702, 0.85898293, 0.83656072, 0.85443478, 0.02998385],
       [0.86435206, 0.85683434, 0.85381852, 0.8558576 , 0.01930215],
       [0.86145646, 0.85554516, 0.84667993, 0.853833  , 0.02327992],
       [0.84374492, 0.8485433 , 0.84358108, 0.84879976, 0.01856306],
       [0.85427945, 0.85189702, 0.85370587, 0.85660554, 0.01728722],
       [0.86250991, 0.85580459, 0.83398588, 0.83501031, 0.01937606],
       [0.83242169, 0.84987645, 0.83267312, 0.84700019, 0.02706504],
       [0.85849326, 0.87282636, 0.85856825, 0.86802178, 0.03102221],
       [0.86960248, 0.87464099, 0.86610129, 0.88040523, 0.01727389],
       [0.88820408, 0.88597957, 0.88610863, 0.89484143, 0.01657357],
       [0.88760697, 0.88368625, 0.86131215, 0.86641333, 0.02235908],
       [0.87107844, 0.86621079, 0.

In [71]:
X_test = []
y_test = []

for i in range(60, inputs.shape[0]):
    X_test.append(inputs[i-60:i])
    y_test.append(inputs[i, 0])

In [72]:
X_test, y_test = np.array(X_test), np.array(y_test)
X_test.shape, y_test.shape

((58, 60, 5), (58,))

In [73]:
y_pred = model.predict(X_test)

In [74]:
scaler.scale_

array([5.63345301e-04, 5.56631737e-04, 5.63428151e-04, 5.62375381e-04,
       1.21162615e-08])

In [75]:
scale = 1/5.63345301e-04
scale

1775.110217880383

In [76]:
y_pred = y_pred*scale
y_test = y_test*scale

In [77]:
y_test

array([1708.13023692, 1675.59019794, 1653.22020296, 1690.65025693,
       1738.5701779 , 1736.6601439 , 1704.51024192, 1689.17015393,
       1704.21019293, 1688.78013893, 1702.84019793, 1782.05015888,
       1848.59019783, 1846.27025184, 1871.26024182, 1839.43016384,
       1833.12022684, 1794.53013887, 1796.76024187, 1804.16014386,
       1873.15025682, 2023.59019772, 2019.48009073, 2020.59019773,
       2056.5001097 , 2029.13023672, 2044.80015871, 2050.10020771,
       2040.84019771, 2054.9503047 , 2050.59019771, 2060.9800907 ,
       2069.86021769, 2017.59019773, 1975.60020775, 1992.42015374,
       2018.04014873, 2001.11021774, 2007.11021773, 2026.78013872,
       2017.80015873, 1973.96019275, 2023.71031472, 2051.72008071,
       2020.59019773, 2022.35020772, 2024.65025672, 2035.59019772,
       2012.89024673, 2029.58018772, 2026.62022672, 2011.59019773,
       1992.64024674, 1992.43016374, 2002.29014874, 2015.96031473,
       1995.40025674, 1989.45018275])